import re
import subprocess
from pathlib import Path
from typing import Optional

import requests

from summarize_reports import summarize
from build_prompt import clean_code


# =========================
# CONFIG
# =========================

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "mannix/deepseek-coder-v2-lite-instruct:q5_0"

MAX_ITERATIONS = 3

JAVA_PROJECT_DIR = Path("java-project")

INPUT_FILE = JAVA_PROJECT_DIR / "src/main/java/input/Sample.java"
OUTPUT_FILE = JAVA_PROJECT_DIR / "src/main/java/output/Sample.java"

INPUT_PACKAGE_LINE = "package input;\n"
OUTPUT_PACKAGE_LINE = "package output;\n"

MAVEN_CMD = r"C:\Program Files\apache-maven-3.9.11\bin\mvn.cmd"


# =========================
# FILE HELPERS
# =========================

def read_text_file(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    return path.read_text(encoding="utf-8")


def write_text_file(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def remove_package_line(code: str) -> str:
    lines = code.splitlines()
    lines = [
        line for line in lines
        if not line.strip().startswith("package ")
    ]
    return "\n".join(lines).strip()


def wrap_if_needed(code: str, package_line: str) -> str:
    code = clean_code(code)
    code = remove_package_line(code)

    if re.search(r"\b(class|interface|enum|record)\s+\w+", code):
        return package_line + "\n" + code.strip() + "\n"

    return f"""{package_line}

public class Sample {{
{code}
}}
"""


def write_input_code(code: str):
    wrapped = wrap_if_needed(code, INPUT_PACKAGE_LINE)
    write_text_file(INPUT_FILE, wrapped)
    return wrapped


def write_output_code(code: str):
    wrapped = wrap_if_needed(code, OUTPUT_PACKAGE_LINE)
    write_text_file(OUTPUT_FILE, wrapped)
    return wrapped


def read_output_code() -> str:
    return read_text_file(OUTPUT_FILE)


# =========================
# LLM
# =========================

def clean_llm_output(text: str) -> str:
    if not isinstance(text, str):
        return ""

    text = text.strip()

    # Remove markdown fences if model returns ```java ... ```
    text = re.sub(r"^```(?:java)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)

    return text.strip()


def call_ollama(prompt: str) -> str:
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
    }

    response = requests.post(OLLAMA_URL, json=payload, timeout=300)
    response.raise_for_status()

    data = response.json()
    return clean_llm_output(data.get("response", ""))


def build_initial_prompt(input_code: str) -> str:
    return f"""
You are an expert Java refactoring assistant.

Task:
Refactor the given Java code while strictly preserving its functionality and external behavior.

Constraints:
1. Do NOT change the program behavior.
2. Do NOT remove logic, branches, conditions, exceptions, or side effects.
3. Do NOT introduce new functionality.
4. Keep the code valid Java.
5. Return ONLY Java code.
6. Do not add explanations.
7. Do not add markdown fences.
8. Do not add comments.

Input code:
{input_code}
""".strip()


def build_feedback_prompt(current_code: str, static_summary: str) -> str:
    return f"""
You are an expert Java refactoring assistant.

The following Java code was generated by a previous refactoring attempt.

Your task:
Improve the code by fixing the static analysis issues listed below, while strictly preserving the same behavior.

Constraints:
1. Do NOT change the program behavior.
2. Do NOT remove required logic.
3. Do NOT introduce new functionality.
4. Fix only the issues that are safe to fix.
5. Return ONLY valid Java code.
6. Do not add explanations.
7. Do not add markdown fences.
8. Do not add comments.

Static analysis issues:
{static_summary}

Current code:
{current_code}
""".strip()


def apply_llm(prompt: str) -> str:
    generated_code = call_ollama(prompt)
    cleaned = clean_code(generated_code)
    write_output_code(cleaned)
    return cleaned


# =========================
# STATIC ANALYSIS
# =========================

def run_static_analysis():
    """
    Runs the full static analysis normally.

    Important:
    SpotBugs needs compiled .class files, so we run:
    clean compile pmd:pmd checkstyle:checkstyle spotbugs:spotbugs
    """

    cmd = f'"{MAVEN_CMD}" clean compile pmd:pmd checkstyle:checkstyle spotbugs:spotbugs'

    result = subprocess.run(
        cmd,
        cwd=JAVA_PROJECT_DIR,
        capture_output=True,
        text=True,
        shell=True,
    )

    return result.returncode, result.stdout + "\n" + result.stderr


def count_issues(summary: str) -> int:
    if not summary or summary.strip() == "✅ No issues found.":
        return 0

    total = 0

    for line in summary.splitlines():
        match = re.search(r":\s*(\d+)\s+occurrence", line)
        if match:
            total += int(match.group(1))

    return total


# =========================
# PIPELINE
# =========================

def run_pipeline():
    print("\n==============================")
    print("Running refactoring pipeline")
    print("==============================")

    original_code = read_text_file(INPUT_FILE)

    # Normalize input file into package input
    input_code = write_input_code(original_code)

    print("\n=== Iteration 1: Initial refactoring ===")

    initial_prompt = build_initial_prompt(input_code)

    apply_llm(initial_prompt)

    best_code: Optional[str] = None
    best_summary: str = ""
    best_issue_count: Optional[int] = None

    for iteration in range(1, MAX_ITERATIONS + 1):
        print(f"\n=== Static analysis iteration {iteration} ===")

        returncode, _ = run_static_analysis()

        if returncode != 0:
            print("⚠️ Maven command returned non-zero.")
            print("This may mean compilation failed or one tool failed.")

        summary = summarize()

        if not summary.strip():
            print("⛔ No static analysis summary found. Stopping.")
            break

        issue_count = count_issues(summary)

        print("\n=== Static Analysis Summary ===")
        print(summary)
        print(f"\nTotal issues: {issue_count}")

        current_code = read_output_code()

        if best_issue_count is None:
            best_issue_count = issue_count
            best_summary = summary
            best_code = current_code

        elif issue_count >= best_issue_count:
            print("\n⛔ Issues stayed the same or increased. Reverting to best code and stopping.")
            write_output_code(best_code)
            break

        else:
            print(f"\n✅ Issues improved: {best_issue_count} → {issue_count}")
            best_issue_count = issue_count
            best_summary = summary
            best_code = current_code

        if issue_count == 0:
            print("\n✅ No issues found. Pipeline finished.")
            break

        if iteration == MAX_ITERATIONS:
            print("\n✅ Reached maximum iterations.")
            break

        print("\n🔁 Sending static-analysis feedback to LLM...")

        feedback_prompt = build_feedback_prompt(
            current_code=current_code,
            static_summary=summary,
        )

        apply_llm(feedback_prompt)

    print("\n==============================")
    print("Final result")
    print("==============================")
    print(f"Final output file: {OUTPUT_FILE}")

    if best_issue_count is not None:
        print(f"Best issue count: {best_issue_count}")

    print("\nFinal summary:")
    print(best_summary)

    report_path = Path("results/single_pipeline_report.txt")
    report_path.parent.mkdir(parents=True, exist_ok=True)

    final_code = read_output_code()

    report_content = f"""
==============================
Refactoring Report
==============================

Final output file:
{OUTPUT_FILE}

Best issue count:
{best_issue_count}

Final static analysis summary:
{best_summary}

==============================
Final Refactored Code
==============================

{final_code}
""".strip()

    report_path.write_text(report_content, encoding="utf-8")

    print(f"\nReport saved to: {report_path}")       


# =========================
# MAIN
# =========================

if __name__ == "__main__":
    run_pipeline()